column_mapping:
  Schistocytes (RBC Fragments): Schistocytes
  Acanthocytes (Spur): Acanthocytes
  Acanthocytes (spur): Acanthocytes
  Basophilic Stippling: Basophilic stippling
  Bite Cells: Bite cells
  Blister Cells: Blister cells
  Dacrocytes/Tear Drop: Tear drop cells
  Teardrop cells: Tear drop cells
  Echinocytes (Burr): Echinocytes
  Burr-cells: Echinocytes
  Howell-Jolly Bodies: Howell-Jolly
  Howell-Jolly bodies: Howell-Jolly
  Pappenheimer Bodies: Pappenheimer
  Sickle Cells: Sickle cells
  Target Cells: Target cells
  Parasites/Micro-organisms: Parasites
  Micro-organisms (Parasites): Parasites
  RBC Agglutination: RBC agglutination













